### ISSUE TITLE
Small fixes for Phone Call

### ISSUE THREAD

**Issue by astralvoid-dev** [notfirefox/swea-project#14]
## Phone Call
This task was completed in the 1st Sprint, but after some discussion, we have come to the conclusion that it needs some fixes.

### To-Do
- [x] Delete the WhatsApp Call Use Case and everything that is linked to it.
- [x] Delete the WhatsApp and Account classes
- [x] Delete the WhatsApp branch in the Activity Diagram
- [x] Add a branch for dialing a number in the Sequence Diagram
- [x] Add a UI Prototype for dialing a number

**Comment by astralvoid-dev** [comment]
All fixes done.
